apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: f1-race-predictor
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "5"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 10
      timeoutSeconds: 300
      containers:
        - image: us-docker.pkg.dev/jowin-personal-2026/f1-race-predictor/f1-race-predictor:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
          env:
            - name: PORT
              value: "8080"
            - name: F1_LOAD_FROM_GCS
              value: "true"
            - name: F1_GCS_BUCKET
              value: "f1-predictor-artifacts-jowin"
